sudo: required
services:
    - docker

before_install:
    - docker build -t anhtran81/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anhtran81/docker-react npm run test -- --coverage